<?php

namespace Database\Seeders\AssessmentQuestions;

final class IlmuKomunikasiQuestionBank implements AssessmentQuestionBank
{
    public static function studyProgram(): string
    {
        return 'Ilmu Komunikasi';
    }

    public static function questions(): array
    {
        return [
            'ikom-media-relations' => [
                [
                    'Tujuan utama media relations bagi sebuah organisasi adalah?',
                    'Membangun hubungan profesional yang berkelanjutan dengan media agar informasi organisasi dapat disampaikan secara akurat',
                    'Memastikan seluruh pemberitaan tentang organisasi selalu positif',
                    'Mengendalikan keputusan editorial setiap media',
                    'Menggantikan seluruh fungsi komunikasi internal organisasi',
                ],
                [
                    'Sebelum mengirimkan press release kepada media, praktisi public relations sebaiknya terlebih dahulu?',
                    'Memastikan informasi memiliki nilai berita, akurat, dan relevan dengan media yang dituju',
                    'Mengirimkan materi yang sama ke seluruh media tanpa mempertimbangkan karakter audiens',
                    'Menghilangkan sumber informasi agar berita lebih singkat',
                    'Meminta media menjamin bahwa berita pasti diterbitkan',
                ],
                [
                    'Seorang jurnalis meminta konfirmasi mengenai isu perusahaan yang sedang berkembang. Respons media relations yang paling tepat adalah?',
                    'Memberikan informasi terverifikasi sesuai kewenangan atau menjadwalkan narasumber yang kompeten',
                    'Mengabaikan permintaan sampai isu menghilang dengan sendirinya',
                    'Memberikan jawaban berdasarkan asumsi agar respons lebih cepat',
                    'Meminta jurnalis menggunakan informasi dari media sosial perusahaan saja',
                ],
                [
                    'Media monitoring dalam kegiatan public relations terutama digunakan untuk?',
                    'Memantau pemberitaan, isu, sentimen, dan konteks pembicaraan mengenai organisasi',
                    'Menentukan harga iklan pada seluruh media',
                    'Menggantikan proses evaluasi komunikasi organisasi',
                    'Menghapus pemberitaan negatif dari internet secara otomatis',
                ],
                [
                    'Saat menyusun media list untuk sebuah kampanye teknologi, kriteria paling relevan adalah?',
                    'Beat jurnalis, karakter media, audiens, dan relevansi topik',
                    'Jumlah pengikut pribadi jurnalis saja',
                    'Lokasi kantor media saja tanpa mempertimbangkan topik',
                    'Urutan alfabet nama media',
                ],
                [
                    'Sebuah organisasi ingin meningkatkan kualitas hubungannya dengan jurnalis. Pendekatan yang paling tepat adalah?',
                    'Memberikan informasi yang kredibel, responsif terhadap kebutuhan media, dan menjaga hubungan secara konsisten',
                    'Menghubungi jurnalis hanya saat organisasi membutuhkan publikasi',
                    'Mengirimkan press release sebanyak mungkin tanpa segmentasi',
                    'Mensyaratkan jurnalis menerbitkan seluruh informasi yang diberikan organisasi',
                ],
            ],
            'ikom-corporate-communication' => [
                [
                    'Corporate communication berfungsi terutama untuk?',
                    'Mengelola komunikasi organisasi secara terpadu dengan stakeholder internal dan eksternal',
                    'Mengelola penjualan produk secara langsung saja',
                    'Menggantikan seluruh fungsi operasional perusahaan',
                    'Menyusun laporan keuangan perusahaan',
                ],
                [
                    'Agar pesan perusahaan konsisten di berbagai kanal, organisasi membutuhkan?',
                    'Pesan utama, identitas komunikasi, dan pedoman yang selaras antar kanal',
                    'Pesan berbeda untuk setiap kanal tanpa keterkaitan',
                    'Perubahan identitas setiap kali membuat publikasi',
                    'Penghapusan proses koordinasi antar bagian komunikasi',
                ],
                [
                    'Komunikasi internal yang efektif ketika perusahaan melakukan perubahan kebijakan sebaiknya?',
                    'Menjelaskan alasan, dampak, waktu pelaksanaan, serta menyediakan ruang untuk pertanyaan',
                    'Menyampaikan perubahan setelah kebijakan diberlakukan tanpa penjelasan',
                    'Membatasi informasi hanya kepada manajemen puncak',
                    'Mengandalkan rumor agar informasi menyebar secara alami',
                ],
                [
                    'Stakeholder mapping membantu corporate communication untuk?',
                    'Mengidentifikasi stakeholder berdasarkan pengaruh, kepentingan, kebutuhan, dan strategi komunikasi',
                    'Menentukan seluruh stakeholder harus menerima pesan yang identik',
                    'Mengurangi kebutuhan untuk mengevaluasi komunikasi',
                    'Menentukan struktur gaji karyawan',
                ],
                [
                    'Hubungan antara corporate identity dan corporate image yang paling tepat adalah?',
                    'Corporate identity adalah bagaimana organisasi menampilkan dirinya, sedangkan corporate image adalah persepsi publik terhadap organisasi',
                    'Corporate identity dan corporate image selalu memiliki arti yang sama',
                    'Corporate image sepenuhnya ditentukan oleh logo perusahaan',
                    'Corporate identity hanya berkaitan dengan laporan keuangan',
                ],
            ],
            'ikom-crisis-communication' => [
                [
                    'Langkah awal yang penting ketika organisasi menghadapi krisis komunikasi adalah?',
                    'Memverifikasi fakta, mengaktifkan tim krisis, dan menentukan respons awal berdasarkan informasi yang tersedia',
                    'Menunggu seluruh percakapan publik berhenti sebelum bertindak',
                    'Menghapus seluruh akun media sosial organisasi',
                    'Menyalahkan pihak lain sebelum penyebab krisis diketahui',
                ],
                [
                    'Holding statement digunakan dalam komunikasi krisis ketika?',
                    'Organisasi perlu memberikan respons awal sementara fakta lengkap masih dikumpulkan',
                    'Organisasi ingin menggantikan seluruh laporan investigasi',
                    'Tidak ada isu yang berkaitan dengan organisasi',
                    'Organisasi ingin menghindari komunikasi dengan stakeholder',
                ],
                [
                    'Pernyataan krisis yang baik seharusnya mengutamakan?',
                    'Fakta yang telah diverifikasi, empati, tindakan yang dilakukan, dan pembaruan berikutnya',
                    'Spekulasi mengenai penyebab yang belum diketahui',
                    'Promosi produk perusahaan',
                    'Penggunaan istilah teknis sebanyak mungkin tanpa penjelasan',
                ],
                [
                    'Dalam situasi krisis yang berdampak pada keselamatan publik, prioritas komunikasi organisasi adalah?',
                    'Keselamatan stakeholder, informasi tindakan yang harus dilakukan, dan pembaruan yang akurat',
                    'Menjaga jumlah unggahan media sosial tetap tinggi',
                    'Mempertahankan slogan kampanye pemasaran',
                    'Membatasi informasi keselamatan agar reputasi tidak terganggu',
                ],
                [
                    'Mengapa satu juru bicara utama sering ditetapkan saat krisis?',
                    'Untuk menjaga konsistensi, akurasi, dan koordinasi pesan organisasi',
                    'Agar seluruh stakeholder hanya dapat mengakses satu media',
                    'Untuk menghilangkan kebutuhan verifikasi informasi',
                    'Agar organisasi tidak perlu melakukan media monitoring',
                ],
                [
                    'Setelah fase utama krisis selesai, organisasi sebaiknya?',
                    'Melakukan evaluasi respons, mengukur dampak reputasi, dan memperbaiki rencana komunikasi krisis',
                    'Menghapus seluruh dokumentasi krisis',
                    'Menghentikan pemantauan publik karena krisis dianggap selesai',
                    'Menggunakan strategi yang sama pada semua krisis berikutnya tanpa evaluasi',
                ],
            ],
            'ikom-news-writing' => [
                [
                    'Dalam penulisan berita straight news, informasi paling penting umumnya ditempatkan pada bagian?',
                    'Lead atau bagian awal berita',
                    'Paragraf terakhir',
                    'Judul foto saja',
                    'Catatan internal reporter',
                ],
                [
                    'Unsur 5W+1H dalam penulisan berita terdiri dari?',
                    'What, Who, When, Where, Why, dan How',
                    'Write, Watch, Work, Where, Why, dan Hear',
                    'What, Who, Which, Where, Website, dan How',
                    'Writer, Word, When, Where, Why, dan Headline',
                ],
                [
                    'Prinsip piramida terbalik dalam berita berarti?',
                    'Informasi disusun dari yang paling penting menuju detail pendukung',
                    'Informasi disusun berdasarkan urutan alfabet',
                    'Kesimpulan selalu ditempatkan sebelum judul',
                    'Semua paragraf harus memiliki panjang yang sama',
                ],
                [
                    'Lead berita yang efektif sebaiknya?',
                    'Ringkas, jelas, menarik, dan memuat inti informasi terpenting',
                    'Memuat seluruh detail berita dalam satu kalimat panjang',
                    'Berisi opini pribadi reporter',
                    'Menghindari fakta utama agar pembaca penasaran',
                ],
                [
                    'Penggunaan kutipan langsung dalam berita paling tepat ketika?',
                    'Pernyataan narasumber memiliki nilai penting dan kata-katanya relevan dipertahankan secara langsung',
                    'Reporter ingin menggantikan seluruh penjelasan fakta',
                    'Informasi belum diverifikasi tetapi terdengar menarik',
                    'Reporter ingin memasukkan pendapat pribadinya',
                ],
                [
                    'Judul berita yang baik seharusnya?',
                    'Mewakili isi berita secara akurat, jelas, dan tidak menyesatkan',
                    'Dibuat sensasional walaupun tidak sesuai isi berita',
                    'Menyembunyikan subjek utama berita',
                    'Menggunakan klaim yang tidak terdapat dalam isi berita',
                ],
            ],
            'ikom-journalistic-interview' => [
                [
                    'Sebelum melakukan wawancara jurnalistik, reporter sebaiknya?',
                    'Melakukan riset mengenai topik dan narasumber serta menyiapkan pertanyaan',
                    'Langsung melakukan wawancara tanpa memahami topik',
                    'Menentukan jawaban narasumber terlebih dahulu',
                    'Mengandalkan pertanyaan tertutup untuk seluruh wawancara',
                ],
                [
                    'Pertanyaan terbuka dalam wawancara jurnalistik berguna untuk?',
                    'Mendorong narasumber memberikan penjelasan yang lebih lengkap',
                    'Membatasi jawaban hanya menjadi ya atau tidak',
                    'Menghindari informasi tambahan dari narasumber',
                    'Menggantikan seluruh proses verifikasi',
                ],
                [
                    'Jika jawaban narasumber belum jelas, reporter sebaiknya menggunakan?',
                    'Pertanyaan lanjutan untuk meminta klarifikasi atau detail tambahan',
                    'Asumsi pribadi untuk melengkapi jawaban',
                    'Jawaban dari wawancara lain tanpa konfirmasi',
                    'Pertanyaan yang tidak berhubungan agar topik berubah',
                ],
                [
                    'Saat narasumber memberikan klaim faktual penting, reporter sebaiknya?',
                    'Memeriksa klaim tersebut menggunakan sumber atau data lain yang relevan',
                    'Langsung menganggap semua pernyataan narasumber sebagai fakta',
                    'Menghapus klaim tersebut tanpa mengevaluasinya',
                    'Menambahkan opini reporter untuk memperkuat klaim',
                ],
                [
                    'Dalam wawancara mengenai isu sensitif, reporter sebaiknya?',
                    'Tetap kritis tetapi menggunakan pertanyaan yang jelas, profesional, dan menghormati narasumber',
                    'Mengintimidasi narasumber agar memberikan jawaban',
                    'Menyembunyikan konteks wawancara',
                    'Mengubah jawaban narasumber agar sesuai dengan sudut berita',
                ],
            ],
            'ikom-news-reporting' => [
                [
                    'Dalam proses news reporting, verifikasi informasi diperlukan untuk?',
                    'Memastikan informasi yang dipublikasikan memiliki dasar fakta yang dapat dipertanggungjawabkan',
                    'Membuat proses publikasi selalu lebih cepat',
                    'Memastikan seluruh sumber memiliki pendapat sama',
                    'Mengurangi kebutuhan reporter memahami konteks',
                ],
                [
                    'Jika dua sumber memberikan informasi yang saling bertentangan, reporter sebaiknya?',
                    'Melakukan verifikasi tambahan, mencari sumber lain, dan menjelaskan perbedaan jika relevan',
                    'Memilih informasi yang paling menarik tanpa verifikasi',
                    'Menggabungkan kedua pernyataan menjadi fakta baru',
                    'Menghapus seluruh informasi dari kedua sumber',
                ],
                [
                    'Atribusi sumber dalam laporan berita berguna untuk?',
                    'Menjelaskan asal informasi dan meningkatkan transparansi terhadap pembaca',
                    'Menyembunyikan pihak yang bertanggung jawab atas informasi',
                    'Menggantikan proses pengecekan fakta',
                    'Membuat semua sumber menjadi anonim',
                ],
                [
                    'Ketika melaporkan peristiwa di lapangan, reporter perlu membedakan antara?',
                    'Fakta yang diamati, pernyataan sumber, dan interpretasi',
                    'Judul dan nama reporter saja',
                    'Berita dan iklan saja',
                    'Foto dan video saja',
                ],
                [
                    'Prinsip keberimbangan dalam peliputan isu kontroversial berarti?',
                    'Memberikan konteks yang proporsional dan kesempatan yang wajar kepada pihak relevan untuk memberikan informasi',
                    'Memberikan jumlah kata yang selalu identik kepada semua pihak tanpa melihat relevansinya',
                    'Menghindari seluruh topik yang memiliki konflik',
                    'Menerbitkan satu versi informasi tanpa meminta tanggapan pihak terkait',
                ],
            ],
            'ikom-content-creation' => [
                [
                    'Langkah awal sebelum membuat konten digital untuk sebuah kampanye adalah?',
                    'Menentukan tujuan komunikasi dan memahami target audiens',
                    'Memilih efek visual sebanyak mungkin',
                    'Mengunggah konten sebelum menentukan pesan',
                    'Mengikuti semua tren tanpa melihat tujuan kampanye',
                ],
                [
                    'Content pillar digunakan untuk?',
                    'Menentukan tema utama yang menjadi dasar pengembangan konten secara konsisten',
                    'Menentukan password akun media sosial',
                    'Menghapus kebutuhan perencanaan konten',
                    'Menggantikan seluruh analisis audiens',
                ],
                [
                    'Call to action dalam sebuah konten berfungsi untuk?',
                    'Mengarahkan audiens melakukan tindakan tertentu setelah menerima pesan',
                    'Menjelaskan sejarah organisasi secara lengkap',
                    'Menggantikan headline konten',
                    'Menentukan algoritma platform',
                ],
                [
                    'Konten yang efektif untuk audiens tertentu sebaiknya?',
                    'Menyesuaikan pesan, format, bahasa, dan kanal dengan karakter serta kebutuhan audiens',
                    'Menggunakan format yang sama untuk semua kelompok audiens',
                    'Mengutamakan preferensi pembuat konten dibanding kebutuhan audiens',
                    'Menghindari evaluasi respons audiens',
                ],
                [
                    'Sebuah konten mendapatkan banyak impressions tetapi sangat sedikit interaksi. Hal yang paling tepat dilakukan adalah?',
                    'Mengevaluasi relevansi pesan, kreativitas, call to action, dan kesesuaiannya dengan audiens',
                    'Menganggap performa sudah maksimal karena impressions tinggi',
                    'Menghapus seluruh data performa sebelumnya',
                    'Mengubah identitas merek pada setiap unggahan berikutnya',
                ],
                [
                    'Agar identitas merek tetap konsisten dalam content creation, pembuat konten perlu memperhatikan?',
                    'Tone of voice, visual identity, pesan utama, dan brand guideline',
                    'Jumlah hashtag saja',
                    'Durasi proses desain saja',
                    'Jenis perangkat yang digunakan pembuat konten',
                ],
            ],
            'ikom-social-media-management' => [
                [
                    'Tujuan content calendar dalam social media management adalah?',
                    'Merencanakan jadwal, tema, format, kanal, dan tujuan publikasi secara terstruktur',
                    'Menjamin setiap konten pasti viral',
                    'Menggantikan proses evaluasi performa',
                    'Membatasi akun hanya pada satu jenis konten',
                ],
                [
                    'Engagement rate terutama digunakan untuk melihat?',
                    'Tingkat interaksi audiens terhadap konten dibandingkan dengan basis pengukuran yang digunakan',
                    'Jumlah seluruh penduduk di wilayah audiens',
                    'Biaya produksi konten secara langsung',
                    'Jumlah perangkat yang digunakan admin',
                ],
                [
                    'Jika tujuan kampanye adalah meningkatkan kunjungan ke website, metrik yang paling relevan untuk diperhatikan adalah?',
                    'Link clicks dan click-through rate',
                    'Jumlah warna pada desain konten',
                    'Jumlah administrator akun',
                    'Durasi proses penulisan caption',
                ],
                [
                    'Ketika muncul komentar negatif yang valid mengenai layanan organisasi, admin media sosial sebaiknya?',
                    'Merespons secara profesional, mengakui masalah bila sesuai, dan mengarahkan penyelesaian melalui prosedur yang tepat',
                    'Menghapus seluruh komentar negatif secara otomatis',
                    'Membalas dengan menyerang pengguna',
                    'Mengabaikan semua komentar agar engagement tidak meningkat',
                ],
                [
                    'Social listening berbeda dari sekadar melihat komentar karena social listening juga bertujuan untuk?',
                    'Memantau percakapan, tren, sentimen, dan isu yang berkaitan dengan merek atau topik di berbagai sumber',
                    'Mengubah seluruh komentar menjadi iklan',
                    'Menghitung jumlah desain yang dibuat tim',
                    'Menggantikan kebutuhan strategi komunikasi',
                ],
                [
                    'Hasil analytics menunjukkan konten edukasi memiliki engagement dan saves tertinggi secara konsisten. Keputusan yang paling tepat adalah?',
                    'Menggunakan temuan tersebut untuk mengoptimalkan porsi dan pengembangan konten edukasi sambil tetap menguji format lain',
                    'Mengabaikan data karena semua kategori konten harus memiliki jumlah yang sama',
                    'Menghapus konten edukasi agar feed lebih bervariasi',
                    'Mengubah target audiens tanpa melakukan analisis tambahan',
                ],
            ],
            'ikom-video-production' => [
                [
                    'Tahap pre-production dalam pembuatan video biasanya mencakup?',
                    'Perencanaan konsep, script, storyboard, kebutuhan produksi, dan jadwal',
                    'Color grading dan rendering final saja',
                    'Distribusi video saja',
                    'Evaluasi engagement setelah publikasi saja',
                ],
                [
                    'Storyboard dalam produksi video digunakan untuk?',
                    'Memvisualisasikan urutan shot dan membantu perencanaan pengambilan gambar',
                    'Menggantikan seluruh proses editing',
                    'Menyimpan data analytics media sosial',
                    'Menentukan hak akses akun video',
                ],
                [
                    'Dalam komposisi rule of thirds, frame secara konseptual dibagi menjadi?',
                    'Sembilan bagian untuk membantu menempatkan subjek pada titik atau garis yang menarik secara visual',
                    'Dua bagian horizontal saja',
                    'Empat bagian tanpa mempertimbangkan posisi subjek',
                    'Satu area pusat yang wajib selalu ditempati subjek',
                ],
                [
                    'Jika dialog pada video sulit terdengar karena noise lingkungan, aspek produksi yang paling langsung perlu diperbaiki adalah?',
                    'Perekaman audio, pemilihan mikrofon, dan pengendalian noise',
                    'Jumlah transisi video',
                    'Warna thumbnail',
                    'Jumlah hashtag saat publikasi',
                ],
                [
                    'Tahap post-production video biasanya mencakup?',
                    'Editing gambar dan audio, color correction atau grading, grafis, serta proses finalisasi',
                    'Penentuan tujuan komunikasi sebelum produksi',
                    'Pemilihan lokasi sebelum shooting',
                    'Penyusunan daftar kru sebelum produksi',
                ],
            ],
        ];
    }
}
