<?php

namespace Database\Seeders\AssessmentQuestions;

final class ManajemenQuestionBank implements AssessmentQuestionBank
{
    public static function studyProgram(): string
    {
        return 'Manajemen';
    }

    public static function questions(): array
    {
        return [
            'man-branding' => [
                [
                    'Sebuah merek ingin dikenal sebagai produk premium yang sederhana dan tahan lama. Hal ini terutama berkaitan dengan?',
                    'Brand positioning',
                    'Brand awareness',
                    'Brand extension',
                    'Brand licensing',
                ],
                [
                    'Perusahaan menggunakan pesan, warna, dan gaya komunikasi yang konsisten di seluruh kanal. Tujuan utamanya adalah?',
                    'Memperkuat identitas dan pengenalan merek',
                    'Mengubah segmentasi pasar setiap kanal',
                    'Mengurangi kebutuhan positioning',
                    'Menghilangkan kebutuhan brand strategy',
                ],
                [
                    'Dua produk memiliki fitur hampir sama tetapi perusahaan ingin mereknya dipersepsikan berbeda dari pesaing. Konsep yang paling relevan adalah?',
                    'Brand differentiation',
                    'Brand dilution',
                    'Market penetration',
                    'Product cannibalization',
                ],
                [
                    'Dokumen yang mengatur penggunaan logo, tipografi, warna, dan gaya komunikasi perusahaan disebut?',
                    'Brand guideline',
                    'Marketing funnel',
                    'Sales forecast',
                    'Market research brief',
                ],
                [
                    'Konsumen dapat langsung mengenali suatu merek ketika melihat logo atau mendengar namanya. Kondisi ini menunjukkan tingkat?',
                    'Brand awareness',
                    'Brand dilution',
                    'Price elasticity',
                    'Market saturation',
                ],
                [
                    'Perusahaan meluncurkan kategori produk baru menggunakan nama merek yang sudah kuat. Strategi ini disebut?',
                    'Brand extension',
                    'Brand repositioning',
                    'Market withdrawal',
                    'Reverse branding',
                ],
            ],
            'man-digital-marketing' => [
                [
                    'Kampanye digital bertujuan menghasilkan pendaftaran. Metrik paling langsung untuk mengevaluasi tujuan tersebut adalah?',
                    'Conversion rate pendaftaran',
                    'Impression share saja',
                    'Follower growth',
                    'Average session duration saja',
                ],
                [
                    'Iklan mendapat 10.000 impresi dan 500 klik. Metrik yang membandingkan klik terhadap impresi adalah?',
                    'Click-through rate',
                    'Conversion rate',
                    'Cost per acquisition',
                    'Return on ad spend',
                ],
                [
                    'Dua kampanye menghasilkan pelanggan baru dalam jumlah sama, tetapi kampanye A menggunakan biaya lebih kecil. Metrik yang tepat adalah?',
                    'Cost per acquisition',
                    'Click-through rate',
                    'Bounce rate',
                    'Reach',
                ],
                [
                    'Perusahaan mengeluarkan Rp5 juta untuk iklan dan menghasilkan pendapatan Rp20 juta yang dapat diatribusikan pada iklan tersebut. Metrik yang tepat untuk melihat efektivitas pendapatan terhadap biaya iklan adalah?',
                    'Return on ad spend',
                    'Click-through rate',
                    'Frequency',
                    'Engagement rate',
                ],
                [
                    'Pengunjung telah melihat halaman produk tetapi belum membeli. Strategi untuk menampilkan iklan kembali kepada kelompok tersebut disebut?',
                    'Retargeting',
                    'Organic reach',
                    'Cold prospecting saja',
                    'Brand licensing',
                ],
                [
                    'Tim ingin membandingkan dua versi headline landing page untuk mengetahui versi yang menghasilkan konversi lebih tinggi. Metode yang tepat adalah?',
                    'A/B testing',
                    'Market census',
                    'Brand extension',
                    'Price skimming',
                ],
            ],
            'man-market-research' => [
                [
                    'Perusahaan ingin mengetahui alasan pelanggan berpindah ke kompetitor. Data paling relevan dikumpulkan melalui?',
                    'Wawancara atau survei pelanggan yang berpindah',
                    'Laporan penjualan internal saja',
                    'Data demografi tanpa pertanyaan perilaku',
                    'Observasi kompetitor tanpa berbicara dengan pelanggan',
                ],
                [
                    'Sampel penelitian hanya berasal dari pelanggan paling loyal. Risiko utama metode tersebut adalah?',
                    'Sampling bias',
                    'Measurement reliability',
                    'Random assignment',
                    'Data triangulation',
                ],
                [
                    'Data yang dikumpulkan perusahaan sendiri melalui survei pelanggan termasuk?',
                    'Primary data',
                    'Secondary data',
                    'Derived accounting data',
                    'Public administrative data',
                ],
                [
                    'Penelitian ingin memahami secara mendalam alasan konsumen memilih sebuah merek. Pendekatan yang lebih sesuai adalah?',
                    'Penelitian kualitatif melalui wawancara mendalam',
                    'Menghitung frekuensi pembelian saja',
                    'Menggunakan data transaksi tanpa konteks',
                    'Mengandalkan satu pertanyaan tertutup',
                ],
                [
                    'Agar pertanyaan survei tidak mengarahkan responden ke jawaban tertentu, pertanyaan sebaiknya?',
                    'Netral dan tidak menggunakan leading question',
                    'Menyebut jawaban yang dianggap benar',
                    'Menggabungkan dua pertanyaan berbeda menjadi satu',
                    'Menggunakan istilah ambigu sebanyak mungkin',
                ],
            ],
            'man-financial-planning' => [
                [
                    'Dalam financial planning, proyeksi arus kas terutama digunakan untuk?',
                    'Memperkirakan kemampuan memenuhi kebutuhan kas pada periode mendatang',
                    'Menghitung brand awareness',
                    'Menentukan segmentasi pelanggan',
                    'Mengukur produktivitas karyawan',
                ],
                [
                    'Perusahaan memperkirakan pemasukan dan pengeluaran untuk dua belas bulan berikutnya. Aktivitas tersebut merupakan?',
                    'Budgeting dan financial planning',
                    'Market positioning',
                    'Performance appraisal',
                    'Recruitment planning',
                ],
                [
                    'Perusahaan membuat skenario optimistis, normal, dan pesimistis untuk proyeksi keuangan. Tujuan utamanya adalah?',
                    'Memahami dampak berbagai kondisi terhadap rencana keuangan',
                    'Menentukan satu skenario yang pasti terjadi',
                    'Menghilangkan seluruh ketidakpastian',
                    'Menggantikan laporan keuangan aktual',
                ],
                [
                    'Pendapatan aktual lebih rendah dari proyeksi sementara pengeluaran tetap sama. Langkah yang paling tepat adalah?',
                    'Memperbarui proyeksi arus kas dan menyesuaikan rencana pengeluaran',
                    'Tetap menggunakan anggaran awal tanpa penyesuaian',
                    'Menambah pengeluaran untuk mengejar target pendapatan',
                    'Menghapus data aktual agar proyeksi tetap sesuai',
                ],
                [
                    'Perusahaan memiliki kewajiban jangka pendek besar dalam tiga bulan mendatang. Fokus utama perencanaan keuangan adalah?',
                    'Menjaga likuiditas agar kewajiban dapat dipenuhi tepat waktu',
                    'Meningkatkan aset tetap tanpa melihat kas',
                    'Mengurangi pencatatan kewajiban',
                    'Mengalihkan seluruh dana ke investasi jangka panjang',
                ],
                [
                    'Selisih antara angka anggaran dan realisasi keuangan disebut?',
                    'Budget variance',
                    'Market share',
                    'Brand equity',
                    'Turnover intention',
                ],
            ],
            'man-financial-analysis' => [
                [
                    'Analisis tren laporan keuangan dilakukan terutama untuk?',
                    'Melihat perubahan kinerja dan posisi keuangan dari waktu ke waktu',
                    'Menentukan struktur organisasi',
                    'Mengukur awareness merek',
                    'Menilai kualitas kandidat',
                ],
                [
                    'Pendapatan naik tetapi laba bersih turun. Analisis berikutnya yang paling relevan adalah?',
                    'Memeriksa perubahan biaya dan margin keuntungan',
                    'Hanya melihat jumlah penjualan',
                    'Mengabaikan biaya operasional',
                    'Membandingkan jumlah karyawan saja',
                ],
                [
                    'Perusahaan memiliki laba positif tetapi arus kas operasi terus negatif. Hal yang paling tepat dilakukan adalah?',
                    'Menganalisis kualitas laba dan pergerakan kas perusahaan',
                    'Menganggap perusahaan pasti sehat karena laba positif',
                    'Mengabaikan laporan arus kas',
                    'Menilai perusahaan hanya dari pertumbuhan pendapatan',
                ],
                [
                    'Rasio yang umum digunakan untuk menilai kemampuan perusahaan memenuhi kewajiban jangka pendek adalah?',
                    'Current ratio',
                    'Debt to equity ratio',
                    'Net profit margin',
                    'Return on equity',
                ],
                [
                    'Debt to equity ratio terutama membantu analis memahami?',
                    'Perbandingan pendanaan melalui utang terhadap ekuitas',
                    'Kecepatan penagihan piutang saja',
                    'Margin laba bersih',
                    'Efisiensi penggunaan persediaan',
                ],
            ],
            'man-investment-management' => [
                [
                    'Prinsip dasar hubungan risiko dan imbal hasil dalam investasi adalah?',
                    'Potensi imbal hasil lebih tinggi umumnya disertai risiko lebih tinggi',
                    'Imbal hasil tinggi selalu dapat diperoleh tanpa risiko',
                    'Risiko tidak memengaruhi keputusan investasi',
                    'Semua instrumen memiliki risiko yang sama',
                ],
                [
                    'Investor membagi dana ke beberapa jenis aset dengan karakteristik berbeda. Tujuan utama tindakan tersebut adalah?',
                    'Diversifikasi risiko',
                    'Menghilangkan seluruh risiko',
                    'Menjamin imbal hasil tetap',
                    'Memaksimalkan konsentrasi pada satu aset',
                ],
                [
                    'Metode yang memperhitungkan nilai waktu uang ketika menilai kelayakan investasi adalah?',
                    'Net Present Value',
                    'Payback sederhana saja',
                    'Market share',
                    'Inventory turnover',
                ],
                [
                    'Investor dengan kebutuhan dana dalam satu tahun biasanya perlu mempertimbangkan secara serius?',
                    'Horizon investasi dan toleransi risiko',
                    'Hanya return historis tertinggi',
                    'Popularitas instrumen di media sosial',
                    'Jumlah instrumen tanpa melihat likuiditas',
                ],
                [
                    'Komposisi portofolio berubah jauh dari target karena kenaikan salah satu aset. Tindakan untuk mengembalikan proporsi ke target disebut?',
                    'Portfolio rebalancing',
                    'Market timing',
                    'Brand repositioning',
                    'Cost averaging',
                ],
            ],
            'man-recruitment-selection' => [
                [
                    'Sebelum membuka lowongan, langkah yang paling tepat adalah?',
                    'Menetapkan kebutuhan jabatan dan profil kandidat',
                    'Langsung memasang iklan tanpa analisis pekerjaan',
                    'Menentukan kandidat sebelum kebutuhan jabatan jelas',
                    'Menggunakan kualifikasi dari posisi lain',
                ],
                [
                    'Sebelum menentukan kualifikasi kandidat, perusahaan perlu memahami tugas dan tanggung jawab posisi melalui?',
                    'Job analysis',
                    'Job rotation',
                    'Succession planning',
                    'Performance calibration',
                ],
                [
                    'Agar proses seleksi konsisten dan adil, perusahaan sebaiknya?',
                    'Menggunakan kriteria kompetensi dan metode penilaian terstruktur',
                    'Mengandalkan intuisi pewawancara',
                    'Mengubah kriteria untuk setiap kandidat',
                    'Memilih kandidat berdasarkan kesamaan pribadi dengan pewawancara',
                ],
                [
                    'Pendekatan yang membantu mengurangi penilaian berdasarkan kesan pribadi pewawancara adalah?',
                    'Wawancara terstruktur dengan pertanyaan dan rubrik yang sama',
                    'Wawancara tanpa daftar kompetensi',
                    'Pertanyaan berbeda tanpa dasar jabatan',
                    'Keputusan berdasarkan kesan lima menit pertama',
                ],
                [
                    'Perusahaan membutuhkan kandidat dengan kemampuan teknis khusus yang langka. Strategi sourcing yang paling masuk akal adalah?',
                    'Menggunakan kanal yang relevan dengan komunitas atau profesi target',
                    'Memasang lowongan hanya pada kanal yang tidak digunakan kandidat target',
                    'Mengurangi informasi tentang kompetensi yang dibutuhkan',
                    'Menghentikan pencarian setelah kandidat pertama',
                ],
                [
                    'Sebuah tes seleksi dikatakan memiliki validitas yang baik jika?',
                    'Hasil tes benar-benar berkaitan dengan kompetensi atau kinerja yang ingin diprediksi',
                    'Tes menghasilkan nilai yang sama untuk semua kandidat',
                    'Tes memiliki jumlah soal paling banyak',
                    'Tes membutuhkan waktu paling lama',
                ],
            ],
            'man-performance-management' => [
                [
                    'Sasaran kinerja yang baik seharusnya?',
                    'Spesifik, terukur, relevan, dan memiliki batas waktu',
                    'Umum dan tanpa indikator',
                    'Berubah setiap hari tanpa dasar',
                    'Tidak memiliki hubungan dengan tujuan organisasi',
                ],
                [
                    'Umpan balik kinerja yang efektif sebaiknya?',
                    'Spesifik, berdasarkan perilaku atau hasil, dan memberikan arah perbaikan',
                    'Berdasarkan kesan pribadi tanpa bukti',
                    'Hanya diberikan saat terjadi masalah besar',
                    'Tidak dikaitkan dengan sasaran kerja',
                ],
                [
                    'KPI dalam performance management terutama digunakan untuk?',
                    'Mengukur pencapaian terhadap sasaran yang ditetapkan',
                    'Menggantikan seluruh percakapan kinerja',
                    'Menentukan struktur kompensasi tanpa data lain',
                    'Menghapus kebutuhan target individual',
                ],
                [
                    'Dua manajer memberi standar nilai sangat berbeda kepada tim dengan kinerja serupa. Proses yang dapat membantu menyelaraskan standar adalah?',
                    'Performance calibration',
                    'Job rotation',
                    'Employer branding',
                    'Market segmentation',
                ],
                [
                    'Seorang karyawan terus tidak mencapai target meski sudah mendapat feedback. Langkah berikutnya yang paling tepat adalah?',
                    'Menyusun rencana perbaikan kinerja dengan target dan dukungan yang jelas',
                    'Mengabaikan masalah sampai periode berikutnya',
                    'Mengubah seluruh KPI agar selalu tercapai',
                    'Memberi penilaian tinggi tanpa perbaikan',
                ],
                [
                    'Indikator seperti jumlah prospek baru yang dihubungi sebelum menghasilkan penjualan merupakan contoh?',
                    'Leading indicator',
                    'Lagging indicator',
                    'Financial statement',
                    'Succession metric',
                ],
            ],
            'man-talent-management' => [
                [
                    'Succession planning bertujuan untuk?',
                    'Menyiapkan talenta bagi peran penting di masa depan',
                    'Mengganti seluruh karyawan secara berkala',
                    'Menghapus kebutuhan pengembangan karyawan',
                    'Memusatkan seluruh kemampuan pada satu orang',
                ],
                [
                    'Program pengembangan high-potential employee terutama bertujuan untuk?',
                    'Mempersiapkan kemampuan bagi tanggung jawab yang lebih besar',
                    'Menjamin promosi tanpa evaluasi',
                    'Menggantikan succession planning',
                    'Menghilangkan kebutuhan feedback',
                ],
                [
                    'Perusahaan kehilangan banyak karyawan berkinerja tinggi. Analisis paling relevan adalah?',
                    'Menganalisis faktor retensi, penghargaan, pengembangan, dan peluang karier',
                    'Hanya menambah proses seleksi kandidat baru',
                    'Mengabaikan exit interview',
                    'Mengurangi seluruh program pengembangan',
                ],
                [
                    'Pemetaan kemampuan yang dimiliki karyawan dibanding kemampuan yang dibutuhkan organisasi disebut?',
                    'Competency mapping',
                    'Market mapping',
                    'Financial mapping',
                    'Brand mapping',
                ],
                [
                    'Career path yang jelas dapat membantu talent management terutama karena?',
                    'Karyawan memahami kemungkinan perkembangan peran dan kompetensi yang diperlukan',
                    'Menjamin setiap karyawan memperoleh promosi',
                    'Menghilangkan kebutuhan evaluasi kinerja',
                    'Menggantikan kompensasi dan budaya kerja',
                ],
            ],
        ];
    }
}
