<?php

namespace Database\Seeders\AssessmentQuestions;

final class PsikologiQuestionBank implements AssessmentQuestionBank
{
    public static function studyProgram(): string
    {
        return 'Psikologi';
    }

    public static function questions(): array
    {
        return [
            'psi-employee-behavior' => [
                [
                    'Karyawan mengalami penurunan kepuasan setelah beban kerja meningkat tanpa dukungan tambahan. Faktor yang paling relevan dianalisis adalah?',
                    'Beban kerja, kondisi kerja, dan dukungan organisasi',
                    'Kepribadian saja tanpa melihat situasi kerja',
                    'Kinerja finansial perusahaan saja',
                    'Jumlah tenaga kerja tanpa melihat tuntutan pekerjaan',
                ],
                [
                    'Nilai, norma, dan kebiasaan bersama yang membentuk cara anggota organisasi bertindak disebut?',
                    'Organizational culture',
                    'Organizational structure',
                    'Job specification',
                    'Employee selection',
                ],
                [
                    'Karyawan memiliki kemampuan baik tetapi motivasinya turun setelah merasa kontribusinya tidak dihargai. Faktor yang relevan adalah?',
                    'Motivasi dan persepsi penghargaan',
                    'Kemampuan kognitif semata',
                    'Deskripsi pekerjaan saja',
                    'Jumlah departemen organisasi',
                ],
                [
                    'Peningkatan ketidakhadiran dan keinginan karyawan untuk keluar sebaiknya dianalisis bersama data tentang?',
                    'Kepuasan kerja dan lingkungan kerja',
                    'Demografi tanpa konteks kerja',
                    'Struktur organisasi saja',
                    'Jumlah kandidat rekrutmen',
                ],
                [
                    'Keadaan kelelahan emosional akibat stres kerja berkepanjangan sering dikaitkan dengan?',
                    'Burnout',
                    'Job enrichment',
                    'Organizational citizenship behavior',
                    'Self-efficacy',
                ],
                [
                    'Keterikatan psikologis karyawan terhadap organisasi dan keinginan untuk tetap menjadi anggota disebut?',
                    'Organizational commitment',
                    'Job analysis',
                    'Role ambiguity',
                    'Selection validity',
                ],
            ],
            'psi-organizational-development' => [
                [
                    'Perubahan organisasi sering ditolak. Langkah yang membantu proses perubahan adalah?',
                    'Melibatkan stakeholder dan menjelaskan alasan serta dampak perubahan',
                    'Menyembunyikan tujuan perubahan',
                    'Mengabaikan kekhawatiran anggota',
                    'Mengubah prosedur tanpa komunikasi',
                ],
                [
                    'Sebelum menentukan intervensi organizational development, organisasi sebaiknya?',
                    'Melakukan diagnosis masalah dan kebutuhan organisasi',
                    'Langsung menerapkan intervensi',
                    'Menganggap seluruh unit memiliki masalah sama',
                    'Menentukan hasil sebelum mengumpulkan data',
                ],
                [
                    'Setelah intervensi dilakukan, langkah penting berikutnya adalah?',
                    'Mengevaluasi dampak menggunakan indikator yang relevan',
                    'Menganggap intervensi pasti berhasil',
                    'Menghentikan pengumpulan data',
                    'Mengabaikan feedback anggota',
                ],
                [
                    'Pendekatan organizational development yang berulang melalui diagnosis, tindakan, dan evaluasi dikenal sebagai?',
                    'Action research',
                    'Cross-sectional screening',
                    'Psychometric standardization',
                    'Job grading',
                ],
                [
                    'Salah satu penyebab resistance to change adalah?',
                    'Ketidakpastian terhadap dampak perubahan',
                    'Seluruh karyawan selalu menolak setiap perubahan',
                    'Semua perubahan selalu menurunkan kinerja',
                    'Komunikasi yang baik pasti meningkatkan resistance',
                ],
            ],
            'psi-psychological-assessment' => [
                [
                    'Reliabilitas instrumen psikologi merujuk pada?',
                    'Konsistensi hasil pengukuran',
                    'Ketepatan konstruk yang diukur',
                    'Jumlah item instrumen',
                    'Popularitas instrumen',
                ],
                [
                    'Validitas instrumen berkaitan dengan?',
                    'Sejauh mana instrumen mengukur konstruk yang seharusnya diukur',
                    'Konsistensi skor semata',
                    'Panjang waktu administrasi',
                    'Jumlah responden penelitian',
                ],
                [
                    'Norma pada tes psikologi berguna untuk?',
                    'Memberikan dasar perbandingan skor individu dengan kelompok referensi',
                    'Menentukan diagnosis secara otomatis',
                    'Menghilangkan kebutuhan interpretasi profesional',
                    'Menjamin setiap kelompok memiliki skor sama',
                ],
                [
                    'Sebelum assessment dilakukan, peserta perlu memperoleh informasi yang memadai mengenai tujuan dan prosedur serta memberikan?',
                    'Informed consent',
                    'Social desirability response',
                    'Norm-referenced score',
                    'Random assignment',
                ],
                [
                    'Hasil assessment sebaiknya diinterpretasikan dengan mempertimbangkan?',
                    'Tujuan, konteks, prosedur, dan keterbatasan instrumen',
                    'Satu skor sebagai satu-satunya dasar seluruh keputusan',
                    'Asumsi bahwa seluruh instrumen sempurna',
                    'Interpretasi yang sama untuk seluruh konteks',
                ],
                [
                    'Menggabungkan hasil tes, wawancara, observasi, dan informasi relevan lain membantu?',
                    'Membangun pemahaman yang lebih komprehensif melalui multiple methods',
                    'Menghilangkan seluruh kemungkinan bias',
                    'Membuat reliabilitas tidak diperlukan',
                    'Menggantikan kebutuhan kompetensi assessor',
                ],
            ],
            'psi-counseling-skills' => [
                [
                    'Pertanyaan terbuka dalam konseling bermanfaat karena?',
                    'Memberikan ruang kepada klien menjelaskan pengalaman secara lebih luas',
                    'Membatasi jawaban menjadi ya atau tidak',
                    'Mengontrol seluruh isi percakapan',
                    'Mengurangi kebutuhan mendengarkan klien',
                ],
                [
                    'Active listening ditunjukkan dengan?',
                    'Memperhatikan, mengklarifikasi, dan merespons secara tepat',
                    'Segera memberi saran sebelum klien selesai berbicara',
                    'Mengalihkan topik ketika muncul emosi',
                    'Menilai pengalaman klien berdasarkan asumsi pribadi',
                ],
                [
                    'Teknik merangkum digunakan untuk?',
                    'Menyatukan poin penting pembicaraan dan memastikan pemahaman',
                    'Mengubah makna pernyataan klien',
                    'Menghentikan topik yang sulit',
                    'Memberikan diagnosis',
                ],
                [
                    'Konselor mengulangi inti pernyataan klien dengan kalimat sendiri. Teknik ini disebut?',
                    'Paraphrasing',
                    'Confrontation',
                    'Interpretation',
                    'Advice giving',
                ],
                [
                    'Konselor mengatakan, "Kedengarannya Anda merasa sangat kecewa karena usaha itu tidak dihargai." Teknik ini terutama merupakan?',
                    'Reflection of feeling',
                    'Closed questioning',
                    'Direct advice',
                    'Summarizing seluruh sesi',
                ],
                [
                    'Ketika kebutuhan klien berada di luar kompetensi konselor, tindakan profesional yang tepat adalah?',
                    'Melakukan referral kepada profesional yang kompeten',
                    'Tetap menangani seluruh masalah sendiri',
                    'Mengabaikan kebutuhan tersebut',
                    'Menyampaikan informasi klien kepada pihak lain tanpa dasar',
                ],
            ],
            'psi-interpersonal-communication' => [
                [
                    'Active listening dalam komunikasi interpersonal ditunjukkan dengan?',
                    'Memperhatikan, mengklarifikasi, dan memberi respons sesuai isi pembicaraan',
                    'Menyusun jawaban sebelum lawan bicara selesai',
                    'Memotong pembicaraan untuk mempercepat diskusi',
                    'Menghindari klarifikasi',
                ],
                [
                    'Komunikasi asertif berarti?',
                    'Menyampaikan kebutuhan dan pendapat dengan jelas sambil menghormati orang lain',
                    'Memaksakan kebutuhan sendiri',
                    'Menghindari seluruh perbedaan pendapat',
                    'Selalu mengikuti keinginan pihak lain',
                ],
                [
                    'Bahasa tubuh, ekspresi wajah, dan kontak mata termasuk?',
                    'Komunikasi nonverbal',
                    'Komunikasi tertulis',
                    'Komunikasi massa',
                    'Komunikasi formal saja',
                ],
                [
                    'Pernyataan "Saya kesulitan berkonsentrasi ketika rapat sering terpotong" merupakan contoh pendekatan?',
                    'I-message yang menjelaskan pengalaman tanpa langsung menyalahkan',
                    'Komunikasi agresif',
                    'Passive avoidance',
                    'Labeling personal',
                ],
                [
                    'Saat konflik terjadi, pendekatan yang konstruktif adalah?',
                    'Mendengarkan kepentingan kedua pihak dan mencari solusi yang dapat diterima',
                    'Berfokus memenangkan argumen',
                    'Menggunakan serangan personal',
                    'Menghindari komunikasi secara permanen',
                ],
            ],
            'psi-emotional-intelligence' => [
                [
                    'Kemampuan menahan respons impulsif ketika marah merupakan bagian dari?',
                    'Self-regulation',
                    'Self-awareness',
                    'Empathy',
                    'Social awareness',
                ],
                [
                    'Kemampuan memahami perasaan orang lain dari sudut pandangnya berkaitan dengan?',
                    'Empathy',
                    'Self-regulation',
                    'Achievement orientation',
                    'Impulse control saja',
                ],
                [
                    'Kemampuan mengenali emosi diri dan pengaruhnya terhadap perilaku disebut?',
                    'Self-awareness',
                    'Social skill',
                    'Empathy',
                    'Conflict management',
                ],
                [
                    'Kemampuan membangun hubungan dan mengelola interaksi sosial secara efektif berkaitan dengan?',
                    'Social skills',
                    'Self-awareness saja',
                    'Cognitive ability saja',
                    'Psychometric validity',
                ],
                [
                    'Tetap berupaya mencapai tujuan meski menghadapi hambatan merupakan aspek yang berkaitan dengan?',
                    'Motivation',
                    'Empathy',
                    'Nonverbal communication',
                    'Reliability',
                ],
            ],
            'psi-research-methodology' => [
                [
                    'Definisi operasional variabel dibutuhkan agar?',
                    'Konsep penelitian dapat diukur atau diamati secara jelas',
                    'Hipotesis selalu terbukti',
                    'Semua responden memberi jawaban sama',
                    'Seluruh bias hilang',
                ],
                [
                    'Hipotesis penelitian pada dasarnya merupakan?',
                    'Pernyataan sementara yang dapat diuji menggunakan data',
                    'Kesimpulan final sebelum penelitian',
                    'Daftar seluruh variabel',
                    'Teknik sampling',
                ],
                [
                    'Pemilihan sampel yang sesuai penting karena?',
                    'Mempengaruhi kualitas inferensi terhadap populasi',
                    'Menjamin hasil selalu signifikan',
                    'Menghilangkan kebutuhan analisis',
                    'Membuat ukuran populasi tidak relevan',
                ],
                [
                    'Dalam eksperimen, peserta dibagi secara acak ke kelompok perlakuan dan kontrol. Tujuan random assignment adalah?',
                    'Mengurangi pengaruh perbedaan awal antar kelompok',
                    'Menjamin semua peserta memberikan respons sama',
                    'Menggantikan random sampling',
                    'Membuktikan hipotesis secara otomatis',
                ],
                [
                    'Variabel lain yang berhubungan dengan variabel independen dan dependen sehingga dapat mengacaukan interpretasi hubungan disebut?',
                    'Confounding variable',
                    'Dependent variable',
                    'Operational definition',
                    'Sampling frame',
                ],
                [
                    'Penelitian yang melibatkan manusia perlu memastikan risiko, kerahasiaan, dan persetujuan partisipan sebagai bagian dari?',
                    'Etika penelitian',
                    'Statistical power',
                    'Randomization',
                    'Construct validity saja',
                ],
            ],
            'psi-interview-observation' => [
                [
                    'Pewawancara hanya mencari informasi yang mendukung dugaan awalnya. Hal tersebut berisiko menimbulkan?',
                    'Confirmation bias',
                    'Recall bias',
                    'Sampling error',
                    'Social facilitation',
                ],
                [
                    'Dua observer memberikan skor sangat berbeda untuk perilaku yang sama. Aspek yang perlu ditingkatkan adalah?',
                    'Inter-rater reliability',
                    'Internal consistency',
                    'Face validity',
                    'Sampling adequacy',
                ],
                [
                    'Catatan observasi yang baik sebaiknya?',
                    'Membedakan deskripsi perilaku yang diamati dari interpretasi observer',
                    'Menggabungkan fakta dan interpretasi tanpa pembeda',
                    'Hanya mencatat kesimpulan',
                    'Ditulis lama setelah kejadian berdasarkan ingatan',
                ],
                [
                    'Wawancara terstruktur ditandai oleh?',
                    'Pertanyaan dan prosedur yang relatif konsisten antar peserta',
                    'Pertanyaan sepenuhnya spontan tanpa kerangka',
                    'Tidak adanya tujuan pengumpulan informasi',
                    'Interpretasi tanpa pencatatan respons',
                ],
                [
                    'Observer mengetahui hipotesis dan tanpa sadar mencatat perilaku yang sesuai harapan penelitian. Risiko ini disebut?',
                    'Observer bias',
                    'Random error saja',
                    'Test-retest reliability',
                    'External validity',
                ],
            ],
            'psi-survey-data-analysis' => [
                [
                    'Skala Likert umumnya digunakan untuk mengukur?',
                    'Tingkat sikap atau persetujuan terhadap pernyataan',
                    'Waktu reaksi dalam milidetik',
                    'Kategori nominal tanpa urutan',
                    'Frekuensi fisiologis',
                ],
                [
                    'Analisis deskriptif digunakan terutama untuk?',
                    'Merangkum dan menggambarkan karakteristik data',
                    'Membuktikan seluruh hubungan kausal',
                    'Menggeneralisasi tanpa memperhatikan sampel',
                    'Menggantikan proses data cleaning',
                ],
                [
                    'Sebelum menganalisis hasil survei, data sebaiknya diperiksa untuk?',
                    'Menemukan missing value, nilai tidak valid, dan inkonsistensi',
                    'Mengubah jawaban agar sesuai hipotesis',
                    'Menghapus respons yang berbeda dari mayoritas',
                    'Mengabaikan outlier tanpa pemeriksaan',
                ],
                [
                    'Cronbach alpha sering digunakan untuk menilai?',
                    'Internal consistency dari beberapa item yang mengukur konstruk yang sama',
                    'External validity penelitian',
                    'Random sampling',
                    'Perbedaan rata-rata antar kelompok',
                ],
                [
                    'Korelasi positif antara dua variabel berarti?',
                    'Ketika satu variabel cenderung meningkat, variabel lain juga cenderung meningkat',
                    'Variabel pertama pasti menyebabkan variabel kedua',
                    'Kedua variabel tidak memiliki hubungan',
                    'Kedua variabel harus memiliki rata-rata sama',
                ],
                [
                    'Item negatif pada skala kadang memerlukan reverse scoring sebelum total skor dihitung. Tujuannya adalah?',
                    'Menyamakan arah interpretasi skor antar item',
                    'Meningkatkan jumlah responden',
                    'Mengubah skala menjadi nominal',
                    'Menghilangkan kebutuhan uji reliabilitas',
                ],
            ],
        ];
    }
}
