<?php

namespace Database\Seeders\AssessmentQuestions;

final class SistemInformasiQuestionBank implements AssessmentQuestionBank
{
    public static function studyProgram(): string
    {
        return 'Sistem Informasi';
    }

    public static function questions(): array
    {
        return [
            'si-sql-data-processing' => [
                [
                    'Sebuah tabel transaksi memiliki customer_id dan total. Query yang paling tepat untuk menghitung total belanja setiap customer adalah?',
                    'SELECT customer_id, SUM(total) FROM transaksi GROUP BY customer_id',
                    'SELECT customer_id, total FROM transaksi ORDER BY customer_id',
                    'SELECT DISTINCT customer_id, total FROM transaksi',
                    'SELECT customer_id, COUNT(total) FROM transaksi',
                ],
                [
                    'Laporan hanya boleh menampilkan pelanggan yang total transaksinya lebih dari Rp10 juta setelah data dikelompokkan. Klausa yang tepat adalah?',
                    'HAVING',
                    'WHERE',
                    'ORDER BY',
                    'DISTINCT',
                ],
                [
                    'Anda ingin menampilkan seluruh pelanggan termasuk pelanggan yang belum pernah bertransaksi. Jenis JOIN yang paling tepat adalah?',
                    'LEFT JOIN dari pelanggan ke transaksi',
                    'INNER JOIN dari pelanggan ke transaksi',
                    'CROSS JOIN pelanggan dan transaksi',
                    'SELF JOIN pada tabel pelanggan',
                ],
                [
                    'Ekspresi SQL yang paling tepat untuk menghitung jumlah pelanggan unik pada tabel transaksi adalah?',
                    'COUNT(DISTINCT customer_id)',
                    'COUNT(customer_id)',
                    'SUM(customer_id)',
                    'GROUP BY customer_id',
                ],
                [
                    'Anda perlu membatasi hanya transaksi tahun 2026 sebelum data dikelompokkan berdasarkan pelanggan. Klausa yang paling tepat digunakan adalah?',
                    'WHERE',
                    'HAVING',
                    'ORDER BY',
                    'UNION',
                ],
                [
                    'Anda ingin memberi nomor urut transaksi dari nilai terbesar ke terkecil untuk setiap pelanggan tanpa menggabungkan baris transaksi. Fitur SQL yang paling tepat adalah?',
                    'Window function seperti ROW_NUMBER() dengan PARTITION BY',
                    'GROUP BY tanpa fungsi agregasi',
                    'DISTINCT pada seluruh kolom',
                    'UNION ALL antar transaksi',
                ],
            ],
            'si-spreadsheet-data-analysis' => [
                [
                    'Anda memiliki ribuan baris penjualan dan ingin merangkum total per kategori tanpa menulis rumus satu per satu. Fitur yang paling tepat adalah?',
                    'Pivot Table',
                    'Conditional Formatting',
                    'Data Validation',
                    'Freeze Panes',
                ],
                [
                    'Dua tabel memiliki kode produk yang sama dan Anda ingin mengambil nama produk dari tabel referensi berdasarkan kode tersebut. Fungsi yang tepat adalah?',
                    'XLOOKUP atau fungsi lookup sejenis',
                    'SUMIFS',
                    'COUNTIF',
                    'SUBTOTAL',
                ],
                [
                    'Anda ingin menjumlahkan penjualan hanya ketika wilayah dan kategori memenuhi kriteria tertentu. Fungsi yang paling sesuai adalah?',
                    'SUMIFS',
                    'SUM',
                    'COUNTIFS',
                    'AVERAGEIF',
                ],
                [
                    'Rumus akan disalin ke banyak baris tetapi referensi ke sel tarif pajak harus tetap mengarah ke sel yang sama. Jenis referensi yang diperlukan adalah?',
                    'Absolute reference seperti $B$2',
                    'Relative reference seperti B2',
                    'Mixed reference seperti B$2 hanya untuk seluruh kondisi',
                    'Named range yang selalu berubah mengikuti baris',
                ],
                [
                    'Tim ingin membatasi kolom status agar pengguna hanya dapat memilih nilai Baru, Diproses, atau Selesai. Fitur spreadsheet yang paling sesuai adalah?',
                    'Data Validation dengan daftar pilihan',
                    'Conditional Formatting',
                    'Pivot Table',
                    'Goal Seek',
                ],
            ],
            'si-business-intelligence-data-visualization' => [
                [
                    'Dashboard manajemen ingin memantau pencapaian penjualan terhadap target bulanan. Komponen BI yang paling relevan adalah?',
                    'KPI yang menampilkan aktual, target, dan selisih',
                    'Pie chart untuk seluruh transaksi individual',
                    'Scatter plot tanpa variabel pembanding',
                    'Tabel transaksi mentah tanpa agregasi',
                ],
                [
                    'Visualisasi yang paling tepat untuk menunjukkan perubahan penjualan dari Januari sampai Desember adalah?',
                    'Line chart',
                    'Pie chart',
                    'Treemap',
                    'Gauge tunggal',
                ],
                [
                    'Manajemen ingin menyaring dashboard berdasarkan wilayah, tahun, dan kategori tanpa membuat laporan terpisah. Fitur yang paling tepat adalah?',
                    'Filter atau slicer interaktif',
                    'Menghapus data yang tidak sedang dilihat',
                    'Membuat satu database untuk setiap filter',
                    'Mengganti seluruh metrik menjadi teks',
                ],
                [
                    'Dalam model data BI, tabel transaksi penjualan biasanya ditempatkan sebagai?',
                    'Fact table yang terhubung ke dimension table',
                    'Dimension table tanpa ukuran numerik',
                    'Tabel metadata yang tidak memiliki relasi',
                    'Tabel konfigurasi pengguna',
                ],
                [
                    'Pengguna dashboard ingin memulai dari penjualan per provinsi lalu melihat detail sampai kota. Kemampuan BI yang dibutuhkan adalah?',
                    'Drill-down',
                    'Deduplication',
                    'Data masking',
                    'Static filtering',
                ],
            ],
            'si-database-management' => [
                [
                    'Dalam database relasional, foreign key terutama digunakan untuk?',
                    'Menghubungkan data antar tabel dan menjaga integritas referensial',
                    'Menjamin seluruh nilai dalam kolom selalu unik',
                    'Mengurutkan hasil query secara otomatis',
                    'Menggantikan fungsi primary key',
                ],
                [
                    'Pemindahan saldo harus berhasil seluruhnya atau dibatalkan seluruhnya jika salah satu proses gagal. Konsep yang paling relevan adalah?',
                    'Transaction dan atomicity',
                    'Indexing dan sorting',
                    'Replication dan sharding',
                    'Normalization dan denormalization',
                ],
                [
                    'Kolom email sering digunakan pada WHERE dan pencarian mulai lambat saat data membesar. Optimasi yang paling relevan adalah?',
                    'Membuat index yang sesuai',
                    'Menambah foreign key pada email',
                    'Menghapus primary key',
                    'Mengubah seluruh tipe data menjadi TEXT',
                ],
                [
                    'Email pengguna tidak boleh sama pada dua akun berbeda. Constraint yang paling tepat adalah?',
                    'UNIQUE constraint',
                    'DEFAULT constraint',
                    'CHECK constraint tanpa ekspresi unik',
                    'Foreign key constraint',
                ],
                [
                    'Tabel menyimpan nama departemen berulang pada setiap data pegawai sehingga perubahan nama departemen harus dilakukan di banyak baris. Perbaikan desain yang paling tepat adalah?',
                    'Memisahkan departemen ke tabel tersendiri dan menggunakan foreign key',
                    'Menambahkan lebih banyak kolom departemen pada tabel pegawai',
                    'Menyimpan seluruh departemen dalam satu kolom',
                    'Menghapus relasi antar data',
                ],
                [
                    'Strategi paling tepat untuk mengurangi risiko kehilangan data ketika server database rusak adalah?',
                    'Menjalankan backup terjadwal dan menguji proses restore',
                    'Hanya menambah index pada semua kolom',
                    'Mengandalkan cache aplikasi sebagai salinan database',
                    'Menonaktifkan transaction log',
                ],
            ],
            'si-web-development' => [
                [
                    'Frontend perlu mengambil daftar produk dari backend tanpa memuat ulang seluruh halaman. Pendekatan yang paling tepat adalah?',
                    'Memanggil endpoint API melalui HTTP',
                    'Menyimpan seluruh data produk di CSS',
                    'Mengakses file database langsung dari browser',
                    'Menanam seluruh data pada atribut HTML permanen',
                ],
                [
                    'Sebuah endpoint berhasil membuat resource baru pada server. Status HTTP yang paling sesuai adalah?',
                    '201 Created',
                    '200 OK untuk seluruh kasus tanpa membedakan operasi',
                    '204 No Content dengan resource gagal dibuat',
                    '302 Found',
                ],
                [
                    'Data formulir dari browser akan disimpan ke database. Praktik backend yang paling tepat sebelum penyimpanan adalah?',
                    'Melakukan validasi input pada server',
                    'Hanya mengandalkan validasi JavaScript pada browser',
                    'Menyimpan input terlebih dahulu lalu memeriksanya',
                    'Menganggap request terautentikasi selalu valid',
                ],
                [
                    'Operasi HTTP yang umumnya digunakan untuk mengambil data tanpa mengubah resource adalah?',
                    'GET',
                    'POST',
                    'PATCH',
                    'DELETE',
                ],
                [
                    'API mengembalikan data yang akan digunakan aplikasi web dan mobile. Format pertukaran data yang umum digunakan adalah?',
                    'JSON',
                    'CSS',
                    'PNG',
                    'SQL dump',
                ],
                [
                    'Pengguna belum login mencoba mengakses endpoint yang membutuhkan autentikasi. Respons HTTP yang paling tepat adalah?',
                    '401 Unauthorized',
                    '201 Created',
                    '304 Not Modified',
                    '422 Unprocessable Content',
                ],
            ],
            'si-system-analysis-design' => [
                [
                    'Sebelum membangun sistem baru, proses bisnis tiap divisi ternyata berbeda. Langkah awal analis sistem yang paling tepat adalah?',
                    'Menggali kebutuhan dan memetakan proses yang sedang berjalan',
                    'Langsung menentukan framework aplikasi',
                    'Langsung membuat database production',
                    'Mengimplementasikan desain dari sistem lama tanpa validasi',
                ],
                [
                    'Analis ingin mengetahui aktor dan interaksi utama pengguna dengan sistem. Diagram yang paling sesuai adalah?',
                    'Use case diagram',
                    'Entity relationship diagram',
                    'Deployment diagram',
                    'Class diagram',
                ],
                [
                    'Pernyataan "sistem harus memungkinkan pelanggan mengubah alamat pengiriman" termasuk?',
                    'Functional requirement',
                    'Non-functional performance requirement',
                    'Business constraint',
                    'Technical deployment requirement',
                ],
                [
                    'Perusahaan ingin memvisualisasikan urutan aktivitas proses persetujuan cuti dari pengajuan sampai keputusan. Model yang paling sesuai adalah?',
                    'Activity diagram atau BPMN',
                    'ERD',
                    'Class diagram',
                    'Network topology',
                ],
                [
                    'Pernyataan "halaman pencarian harus merespons dalam maksimal dua detik" termasuk?',
                    'Non-functional performance requirement',
                    'Functional requirement',
                    'Data entity requirement',
                    'Use case actor',
                ],
                [
                    'Tim ingin memastikan setiap requirement telah diimplementasikan dan diuji sebelum rilis. Artefak yang paling membantu adalah?',
                    'Requirement traceability matrix',
                    'Color palette',
                    'Database seed sementara',
                    'Daftar package frontend',
                ],
            ],
            'si-ui-design' => [
                [
                    'Tombol utama dan sekunder memiliki tampilan sama kuat sehingga pengguna bingung menentukan tindakan. Prinsip yang perlu diperbaiki adalah?',
                    'Hierarki visual',
                    'Grid database',
                    'Content caching',
                    'Data normalization',
                ],
                [
                    'Teks abu-abu muda pada latar putih sulit dibaca. Aspek UI yang paling perlu diperbaiki adalah?',
                    'Kontras dan keterbacaan',
                    'Information architecture',
                    'Database indexing',
                    'API versioning',
                ],
                [
                    'Komponen dengan fungsi sama terlihat berbeda pada setiap halaman. Prinsip yang perlu diperbaiki adalah?',
                    'Konsistensi antarmuka',
                    'Progressive disclosure',
                    'Data redundancy',
                    'Server-side caching',
                ],
                [
                    'Pengguna salah mengisi format email. Respons antarmuka yang paling membantu adalah?',
                    'Menampilkan pesan kesalahan yang spesifik di dekat field email',
                    'Menghapus seluruh formulir setelah validasi gagal',
                    'Hanya mengubah warna tombol tanpa pesan',
                    'Menunggu pengguna menemukan kesalahannya sendiri',
                ],
                [
                    'Sebuah elemen terlihat seperti tombol tetapi tidak memberikan indikasi bahwa elemen dapat diklik. Prinsip yang berkaitan adalah?',
                    'Affordance',
                    'Normalization',
                    'Pagination database',
                    'Data aggregation',
                ],
                [
                    'Agar pengguna keyboard dapat mengetahui komponen mana yang sedang aktif, antarmuka sebaiknya menyediakan?',
                    'Focus indicator yang terlihat jelas',
                    'Animasi hover saja',
                    'Warna latar yang sama untuk seluruh elemen',
                    'Tooltip yang hanya muncul saat mouse digunakan',
                ],
            ],
            'si-wireframing-prototyping' => [
                [
                    'Tujuan utama wireframe pada tahap awal desain adalah?',
                    'Memvalidasi struktur halaman dan prioritas konten sebelum detail visual',
                    'Menentukan identitas visual final',
                    'Menghasilkan kode production',
                    'Menentukan skema database final',
                ],
                [
                    'Tim ingin mencoba beberapa struktur halaman dengan cepat tanpa fokus pada warna dan ilustrasi. Artefak yang paling tepat adalah?',
                    'Low-fidelity wireframe',
                    'High-fidelity prototype final',
                    'Design system lengkap',
                    'Dokumentasi API',
                ],
                [
                    'Sebelum fitur dikembangkan, tim ingin mengetahui apakah pengguna memahami alur pemesanan. Prototype sebaiknya digunakan untuk?',
                    'Menguji alur dan interaksi dengan pengguna',
                    'Menggantikan seluruh implementasi backend',
                    'Menjadi database transaksi sementara',
                    'Menentukan spesifikasi server',
                ],
                [
                    'Tim sedang menentukan hubungan antara halaman Beranda, Produk, Detail Produk, dan Checkout. Aktivitas ini paling berkaitan dengan?',
                    'Information architecture dan user flow',
                    'Visual branding',
                    'Database replication',
                    'Load testing',
                ],
                [
                    'Prototype yang sangat menyerupai produk akhir dan memiliki interaksi mendekati aplikasi sebenarnya disebut?',
                    'High-fidelity prototype',
                    'Low-fidelity sketch',
                    'Content inventory',
                    'Affinity diagram',
                ],
            ],
            'si-user-research' => [
                [
                    'Tim ingin memahami kebutuhan dan hambatan pengguna sebelum merancang fitur. Metode yang paling tepat adalah?',
                    'Wawancara atau observasi pengguna yang relevan',
                    'Menentukan kebutuhan hanya berdasarkan opini internal',
                    'Langsung membuat desain final',
                    'Menggunakan analytics tanpa memahami konteks pengguna',
                ],
                [
                    'Tim ingin mengetahui mengapa pengguna kesulitan menyelesaikan checkout. Metode yang paling tepat adalah?',
                    'Usability testing dengan pengguna target',
                    'Brand audit',
                    'Load testing',
                    'Code review',
                ],
                [
                    'Setelah wawancara, tim memiliki banyak catatan temuan. Teknik yang membantu menemukan tema berulang adalah?',
                    'Affinity mapping',
                    'A/B deployment',
                    'Database normalization',
                    'Regression testing',
                ],
                [
                    'Aplikasi ditujukan untuk mahasiswa baru. Agar hasil riset relevan, peserta penelitian sebaiknya?',
                    'Mewakili karakteristik pengguna target',
                    'Hanya berasal dari tim pengembang',
                    'Dipilih berdasarkan kemudahan tanpa melihat target pengguna',
                    'Hanya terdiri dari pengguna paling berpengalaman',
                ],
                [
                    'Temuan wawancara menunjukkan satu pola, tetapi analytics menunjukkan perilaku yang berbeda. Pendekatan yang paling tepat adalah?',
                    'Membandingkan beberapa sumber data dan menyelidiki perbedaannya',
                    'Mengabaikan salah satu sumber secara otomatis',
                    'Memilih data yang sesuai asumsi awal',
                    'Mengubah kesimpulan sebelum melakukan analisis',
                ],
            ],
        ];
    }
}
