<?php

namespace Database\Seeders\AssessmentQuestions;

final class SistemKomputerQuestionBank implements AssessmentQuestionBank
{
    public static function studyProgram(): string
    {
        return 'Sistem Komputer';
    }

    public static function questions(): array
    {
        return [
            'sk-computer-architecture' => [
                [
                    'Komponen yang mengeksekusi instruksi dan operasi aritmetika-logika terutama berada pada?',
                    'CPU',
                    'RAM',
                    'SSD',
                    'I/O controller',
                ],
                [
                    'Cache memory ditempatkan dekat processor terutama untuk?',
                    'Mengurangi waktu akses terhadap data atau instruksi yang sering digunakan',
                    'Menggantikan seluruh RAM',
                    'Menyimpan data secara permanen',
                    'Menggantikan register CPU',
                ],
                [
                    'Tahapan dasar instruction cycle secara umum mencakup?',
                    'Fetch, decode, dan execute',
                    'Read, write, dan format',
                    'Compile, link, dan deploy',
                    'Input, output, dan storage',
                ],
                [
                    'Register pada processor digunakan terutama untuk?',
                    'Menyimpan data atau operand yang sedang diproses dengan akses sangat cepat',
                    'Menyimpan file pengguna secara permanen',
                    'Menggantikan cache level terakhir',
                    'Menghubungkan CPU dengan jaringan',
                ],
                [
                    'Pipelining pada processor terutama bertujuan untuk?',
                    'Meningkatkan throughput eksekusi instruksi dengan menumpang-tindihkan tahap instruksi',
                    'Menambah kapasitas penyimpanan permanen',
                    'Menghilangkan seluruh branch instruction',
                    'Menjalankan satu instruksi sampai selesai sebelum instruksi lain dimulai',
                ],
                [
                    'Urutan memory hierarchy dari yang umumnya paling cepat ke lebih lambat adalah?',
                    'Register, cache, RAM, storage',
                    'Storage, RAM, cache, register',
                    'RAM, storage, register, cache',
                    'Cache, storage, register, RAM',
                ],
            ],
            'sk-digital-logic' => [
                [
                    'Gerbang AND menghasilkan keluaran 1 ketika?',
                    'Semua input bernilai 1',
                    'Minimal satu input bernilai 1',
                    'Semua input bernilai 0',
                    'Jumlah input bernilai 1 ganjil',
                ],
                [
                    'Gerbang XOR dua input menghasilkan keluaran 1 ketika?',
                    'Kedua input berbeda',
                    'Kedua input sama',
                    'Minimal satu input bernilai 0',
                    'Kedua input selalu 1',
                ],
                [
                    'Komponen digital yang dapat menyimpan satu bit keadaan adalah?',
                    'Flip-flop',
                    'Multiplexer',
                    'Decoder',
                    'Adder',
                ],
                [
                    'Karnaugh Map digunakan terutama untuk?',
                    'Menyederhanakan ekspresi Boolean',
                    'Mengubah sinyal analog menjadi digital',
                    'Menyimpan data biner',
                    'Menghasilkan clock',
                ],
                [
                    'Multiplexer digunakan untuk?',
                    'Memilih satu dari beberapa input untuk diteruskan ke satu output',
                    'Menyimpan satu bit data',
                    'Menghitung operasi aritmetika saja',
                    'Mengubah data serial menjadi storage permanen',
                ],
            ],
            'sk-microprocessor-microcontroller' => [
                [
                    'Dibanding microprocessor umum, microcontroller biasanya mengintegrasikan?',
                    'CPU, memory, dan peripheral dalam satu chip',
                    'CPU saja tanpa peripheral',
                    'GPU dan storage massal saja',
                    'RAM eksternal saja',
                ],
                [
                    'Register pada processor terutama digunakan untuk?',
                    'Menyimpan data sementara yang sedang diproses',
                    'Menyimpan firmware secara permanen',
                    'Menyimpan backup perangkat',
                    'Menyimpan seluruh program aplikasi',
                ],
                [
                    'Interrupt memungkinkan microcontroller untuk?',
                    'Merespons event tanpa harus terus-menerus melakukan polling',
                    'Menambah kapasitas flash',
                    'Mengubah clock menjadi storage',
                    'Menghilangkan seluruh fungsi timer',
                ],
                [
                    'Pin GPIO pada microcontroller digunakan untuk?',
                    'Input atau output digital yang dapat dikendalikan program',
                    'Penyimpanan data permanen',
                    'Menggantikan CPU core',
                    'Menjalankan protokol jaringan tanpa konfigurasi',
                ],
                [
                    'Peripheral timer pada microcontroller dapat digunakan untuk?',
                    'Mengukur interval waktu atau menghasilkan event periodik',
                    'Menyimpan source code',
                    'Menggantikan ADC',
                    'Meningkatkan kapasitas RAM',
                ],
            ],
            'sk-embedded-systems' => [
                [
                    'Pada embedded system real-time, salah satu kebutuhan penting adalah?',
                    'Respons sistem memenuhi batas waktu yang ditentukan',
                    'Setiap tugas boleh selesai kapan saja',
                    'Semua proses harus menggunakan prioritas sama',
                    'Tidak memerlukan pengujian waktu',
                ],
                [
                    'Software yang berjalan untuk mengendalikan hardware embedded sering disebut?',
                    'Firmware',
                    'Middleware web',
                    'Hypervisor desktop',
                    'Spreadsheet macro',
                ],
                [
                    'Embedded system umumnya dirancang untuk?',
                    'Menjalankan fungsi khusus pada perangkat tertentu',
                    'Menjalankan seluruh jenis workload tanpa batas',
                    'Menggantikan server general-purpose',
                    'Selalu menjalankan desktop operating system',
                ],
                [
                    'Mekanisme yang dapat me-reset embedded system ketika program berhenti merespons adalah?',
                    'Watchdog timer',
                    'ADC',
                    'PWM',
                    'UART',
                ],
                [
                    'Interrupt Service Routine sebaiknya umumnya dibuat?',
                    'Singkat dan menyelesaikan pekerjaan kritis secepat mungkin',
                    'Berisi seluruh logika aplikasi yang panjang',
                    'Menunggu operasi blocking selama mungkin',
                    'Menonaktifkan seluruh interrupt secara permanen',
                ],
                [
                    'Pada perangkat bertenaga baterai, salah satu pertimbangan utama desain embedded adalah?',
                    'Konsumsi daya',
                    'Ukuran database cloud saja',
                    'Jumlah halaman antarmuka',
                    'Resolusi desktop monitor',
                ],
            ],
            'sk-internet-of-things' => [
                [
                    'Protokol ringan berbasis publish-subscribe yang banyak digunakan pada IoT adalah?',
                    'MQTT',
                    'SMTP',
                    'FTP',
                    'SNMP',
                ],
                [
                    'Alur IoT yang umum adalah?',
                    'Sensor mengumpulkan data, perangkat memproses atau mengirimnya, lalu aplikasi menggunakan data',
                    'Cloud menghasilkan seluruh data tanpa perangkat',
                    'Actuator selalu menjadi sumber data satu-satunya',
                    'Sensor langsung mengubah konfigurasi internet global',
                ],
                [
                    'Praktik keamanan penting ketika perangkat IoT terhubung ke internet adalah?',
                    'Menggunakan autentikasi dan komunikasi terenkripsi',
                    'Mempertahankan password default',
                    'Membuka seluruh port',
                    'Menonaktifkan pembaruan keamanan',
                ],
                [
                    'Pemrosesan data dekat perangkat sumber sebelum dikirim ke cloud disebut?',
                    'Edge computing',
                    'Batch archiving',
                    'Cold storage',
                    'Database normalization',
                ],
                [
                    'Proses memberikan identitas, credential, dan konfigurasi awal kepada perangkat IoT disebut?',
                    'Device provisioning',
                    'Data visualization',
                    'Packet fragmentation',
                    'Load balancing',
                ],
                [
                    'Perangkat IoT mengirim pembacaan suhu setiap beberapa detik dan kehilangan sesekali masih dapat ditoleransi. Pertimbangan protokol yang penting adalah?',
                    'Menyeimbangkan reliability, bandwidth, dan kebutuhan aplikasi',
                    'Selalu menggunakan protokol paling berat',
                    'Mengirim seluruh histori pada setiap paket',
                    'Menghindari identitas perangkat',
                ],
            ],
            'sk-sensor-actuator-integration' => [
                [
                    'Sensor analog menghasilkan tegangan yang perlu dibaca microcontroller digital. Komponen yang digunakan adalah?',
                    'ADC',
                    'DAC',
                    'PWM',
                    'UART',
                ],
                [
                    'Teknik yang umum digunakan untuk mengatur kecepatan motor DC secara efisien adalah?',
                    'PWM',
                    'ADC',
                    'SPI',
                    'I2C address scanning',
                ],
                [
                    'Kalibrasi sensor dilakukan terutama untuk?',
                    'Meningkatkan kesesuaian hasil pengukuran terhadap nilai referensi',
                    'Mengubah sensor menjadi actuator',
                    'Meningkatkan kapasitas flash',
                    'Menghilangkan seluruh noise secara otomatis',
                ],
                [
                    'Tombol mekanik dapat menghasilkan beberapa transisi singkat ketika ditekan sekali. Penanganan yang diperlukan disebut?',
                    'Debouncing',
                    'Sampling aliasing',
                    'Packet routing',
                    'Clock multiplication',
                ],
                [
                    'Sinyal sensor yang sangat kecil dan berisik sebelum masuk ADC dapat membutuhkan?',
                    'Signal conditioning seperti amplification dan filtering',
                    'Data compression',
                    'Network address translation',
                    'Filesystem caching',
                ],
            ],
            'sk-computer-networks' => [
                [
                    'Perangkat yang meneruskan frame berdasarkan MAC address di jaringan lokal adalah?',
                    'Switch',
                    'Router',
                    'DNS server',
                    'DHCP server',
                ],
                [
                    'Router digunakan terutama untuk?',
                    'Meneruskan packet antar jaringan IP',
                    'Meneruskan frame hanya berdasarkan MAC dalam satu LAN',
                    'Memberikan nama domain',
                    'Menyimpan konfigurasi aplikasi pengguna',
                ],
                [
                    'TCP digunakan ketika aplikasi membutuhkan?',
                    'Pengiriman data yang andal dan berurutan',
                    'Datagram tanpa koneksi dan tanpa retransmission',
                    'Resolusi nama domain',
                    'Pemetaan IP ke MAC saja',
                ],
                [
                    'Komputer akan mengirim paket ke jaringan berbeda dari subnet lokal. Tujuan awal paket adalah?',
                    'Default gateway',
                    'Loopback address',
                    'DNS resolver',
                    'Alamat broadcast sebagai tujuan akhir',
                ],
                [
                    'Alamat IPv4 /24 berarti jumlah bit network prefix adalah?',
                    '24 bit',
                    '8 bit',
                    '16 bit',
                    '32 bit host seluruhnya',
                ],
                [
                    'Protokol yang membantu mengetahui MAC address dari sebuah IPv4 address pada jaringan lokal adalah?',
                    'ARP',
                    'DNS',
                    'DHCP',
                    'HTTP',
                ],
            ],
            'sk-network-administration' => [
                [
                    'VLAN digunakan untuk?',
                    'Membagi jaringan menjadi beberapa segmen logis pada infrastruktur switch',
                    'Menggantikan seluruh routing',
                    'Memberikan IP otomatis',
                    'Mengenkripsi seluruh traffic',
                ],
                [
                    'DHCP digunakan untuk?',
                    'Memberikan konfigurasi IP kepada host secara otomatis',
                    'Menerjemahkan domain ke IP',
                    'Mendeteksi intrusion',
                    'Mengenkripsi koneksi',
                ],
                [
                    'Sebelum mengubah konfigurasi jaringan production, administrator sebaiknya?',
                    'Membuat backup konfigurasi dan rencana rollback',
                    'Menghapus konfigurasi sebelumnya',
                    'Menonaktifkan monitoring',
                    'Mengubah beberapa komponen sekaligus tanpa dokumentasi',
                ],
                [
                    'Monitoring jaringan berguna terutama untuk?',
                    'Mendeteksi gangguan, tren performa, dan kondisi perangkat',
                    'Menggantikan backup konfigurasi',
                    'Menghilangkan kebutuhan logging',
                    'Menjamin jaringan tidak pernah gagal',
                ],
                [
                    'DNS server pada jaringan organisasi digunakan terutama untuk?',
                    'Memetakan nama host atau domain ke alamat yang sesuai',
                    'Mengalokasikan VLAN secara otomatis',
                    'Mengenkripsi seluruh packet',
                    'Menentukan MAC address switch',
                ],
            ],
            'sk-network-security' => [
                [
                    'Enkripsi data selama transmisi terutama menjaga?',
                    'Confidentiality',
                    'Availability',
                    'Redundancy',
                    'Scalability',
                ],
                [
                    'Firewall digunakan terutama untuk?',
                    'Mengontrol traffic berdasarkan aturan keamanan',
                    'Menentukan IP melalui DHCP',
                    'Menyimpan log aplikasi sebagai database',
                    'Menggantikan seluruh autentikasi',
                ],
                [
                    'Sistem yang menganalisis aktivitas jaringan untuk mendeteksi pola serangan disebut?',
                    'Intrusion Detection System',
                    'DHCP server',
                    'Load balancer',
                    'DNS resolver',
                ],
                [
                    'Memisahkan server publik, perangkat pengguna, dan sistem sensitif ke segmen berbeda membantu menerapkan?',
                    'Network segmentation',
                    'Port mirroring saja',
                    'Flat network',
                    'Broadcast amplification',
                ],
                [
                    'Teknologi yang dapat membuat tunnel terenkripsi untuk akses jaringan jarak jauh adalah?',
                    'VPN',
                    'VLAN',
                    'DHCP',
                    'ARP',
                ],
                [
                    'Perangkat jaringan menggunakan firmware dengan kerentanan yang sudah diketahui. Tindakan yang tepat adalah?',
                    'Memperbarui firmware sesuai prosedur dan advisori keamanan',
                    'Menonaktifkan logging',
                    'Membuka seluruh service',
                    'Mengabaikan kerentanan selama perangkat masih menyala',
                ],
            ],
        ];
    }
}
