<?php

namespace Database\Seeders\AssessmentQuestions;

final class TeknikInformatikaQuestionBank implements AssessmentQuestionBank
{
    public static function studyProgram(): string
    {
        return 'Teknik Informatika';
    }

    public static function questions(): array
    {
        return [
            'ti-algorithms-data-structures' => [
                [
                    'Algoritma pencarian yang efisien untuk data yang sudah terurut adalah?',
                    'Binary search',
                    'Linear search',
                    'Bubble sort',
                    'Selection sort',
                ],
                [
                    'Struktur data yang menerapkan First In First Out adalah?',
                    'Queue',
                    'Stack',
                    'Heap',
                    'Binary search tree',
                ],
                [
                    'Kompleksitas waktu binary search pada data terurut adalah?',
                    'O(log n)',
                    'O(n)',
                    'O(n log n)',
                    'O(n²)',
                ],
                [
                    'Struktur data yang menerapkan Last In First Out adalah?',
                    'Stack',
                    'Queue',
                    'Graph',
                    'Hash table',
                ],
                [
                    'Struktur data yang umumnya memberikan pencarian key dengan kompleksitas rata-rata O(1) adalah?',
                    'Hash table',
                    'Linked list',
                    'Unsorted array',
                    'Binary heap',
                ],
                [
                    'Breadth First Search pada graph umumnya menggunakan struktur data?',
                    'Queue',
                    'Stack',
                    'Priority queue untuk seluruh kasus',
                    'Hash set sebagai pengganti antrean',
                ],
            ],
            'ti-object-oriented-programming' => [
                [
                    'Menyembunyikan detail internal object dan menyediakan akses terkontrol disebut?',
                    'Encapsulation',
                    'Inheritance',
                    'Polymorphism',
                    'Abstraction',
                ],
                [
                    'Kemampuan object dengan tipe dasar sama untuk menjalankan implementasi perilaku berbeda disebut?',
                    'Polymorphism',
                    'Encapsulation',
                    'Composition',
                    'Serialization',
                ],
                [
                    'Membuat class baru berdasarkan class yang sudah ada dan mewarisi perilakunya disebut?',
                    'Inheritance',
                    'Encapsulation',
                    'Overloading',
                    'Composition',
                ],
                [
                    'Hubungan ketika sebuah object memiliki object lain sebagai komponennya disebut?',
                    'Composition',
                    'Inheritance',
                    'Recursion',
                    'Casting',
                ],
                [
                    'Interface terutama berguna untuk?',
                    'Mendefinisikan kontrak perilaku yang dapat diimplementasikan berbagai class',
                    'Menyimpan state global aplikasi',
                    'Menggantikan seluruh constructor',
                    'Mencegah class memiliki method',
                ],
            ],
            'ti-software-engineering' => [
                [
                    'Requirement berubah ketika pengembangan sudah berjalan. Praktik yang paling tepat adalah?',
                    'Menganalisis dampak dan memperbarui requirement sebelum menyesuaikan implementasi',
                    'Mengabaikan perubahan requirement',
                    'Menerapkan perubahan langsung ke production',
                    'Menghapus implementasi lama tanpa analisis',
                ],
                [
                    'Tujuan utama automated test adalah?',
                    'Memverifikasi perilaku sistem dan mendeteksi regresi',
                    'Menjamin software tidak pernah memiliki bug',
                    'Menggantikan seluruh proses review',
                    'Menghilangkan kebutuhan requirement',
                ],
                [
                    'Version control seperti Git terutama digunakan untuk?',
                    'Mencatat perubahan source code dan membantu kolaborasi',
                    'Menggantikan database aplikasi',
                    'Mengatur resource server production',
                    'Mengompilasi source code',
                ],
                [
                    'Continuous Integration terutama bertujuan untuk?',
                    'Mengintegrasikan perubahan secara rutin dan menjalankan pemeriksaan otomatis',
                    'Menunggu seluruh fitur selesai sebelum integrasi',
                    'Menghindari automated testing',
                    'Menghapus kebutuhan version control',
                ],
                [
                    'Code review sebelum perubahan digabungkan terutama membantu?',
                    'Menemukan masalah dan meningkatkan kualitas serta maintainability kode',
                    'Menggantikan seluruh automated test',
                    'Menjamin semua requirement selalu benar',
                    'Menghilangkan kebutuhan dokumentasi',
                ],
                [
                    'Acceptance criteria pada user story digunakan untuk?',
                    'Menentukan kondisi yang harus terpenuhi agar fitur dianggap selesai',
                    'Menentukan struktur database seluruh aplikasi',
                    'Menggantikan source code',
                    'Mengatur deployment environment',
                ],
            ],
            'ti-computer-networks' => [
                [
                    'Perangkat mengirim paket ke jaringan di luar subnet lokal. Paket biasanya diarahkan terlebih dahulu ke?',
                    'Default gateway',
                    'DNS server',
                    'Loopback interface',
                    'DHCP server',
                ],
                [
                    'Protokol transport yang menyediakan koneksi, pengurutan, dan retransmission adalah?',
                    'TCP',
                    'UDP',
                    'IP',
                    'ARP',
                ],
                [
                    'Perangkat yang meneruskan frame berdasarkan MAC address pada LAN adalah?',
                    'Switch',
                    'Router',
                    'DNS server',
                    'Firewall aplikasi',
                ],
                [
                    'Layanan yang memetakan nama domain ke alamat IP adalah?',
                    'DNS',
                    'DHCP',
                    'ARP',
                    'NTP',
                ],
                [
                    'Subnet mask digunakan untuk menentukan?',
                    'Bagian network dan host dari alamat IP',
                    'Nomor port aplikasi',
                    'MAC address default gateway',
                    'Nama domain perangkat',
                ],
                [
                    'Aplikasi real-time lebih memprioritaskan latensi rendah daripada retransmission dan dapat mentoleransi kehilangan sebagian paket. Protokol yang sering dipilih adalah?',
                    'UDP',
                    'TCP',
                    'ARP',
                    'ICMP',
                ],
            ],
            'ti-operating-systems' => [
                [
                    'Virtual memory memungkinkan sistem operasi untuk?',
                    'Menggunakan penyimpanan sebagai perluasan logis memori ketika diperlukan',
                    'Menggantikan seluruh fungsi CPU',
                    'Menjamin RAM tidak pernah penuh',
                    'Menghilangkan proses swapping atau paging',
                ],
                [
                    'Perbedaan umum process dan thread adalah?',
                    'Thread dalam process dapat berbagi ruang memori process yang sama',
                    'Setiap thread memiliki sistem operasi sendiri',
                    'Process selalu berbagi seluruh memori dengan process lain',
                    'Thread tidak dapat berjalan secara concurrent',
                ],
                [
                    'Komponen sistem operasi yang menentukan process berikutnya yang memperoleh waktu CPU adalah?',
                    'Scheduler',
                    'Loader',
                    'File system',
                    'Device driver',
                ],
                [
                    'Kondisi ketika dua atau lebih process saling menunggu resource sehingga tidak dapat melanjutkan disebut?',
                    'Deadlock',
                    'Starvation saja',
                    'Paging',
                    'Context switching',
                ],
                [
                    'Paging membagi virtual memory menjadi unit tetap yang disebut?',
                    'Page',
                    'Segment',
                    'Thread',
                    'Socket',
                ],
            ],
            'ti-cybersecurity' => [
                [
                    'Prinsip least privilege berarti?',
                    'Memberikan hak akses minimum yang diperlukan',
                    'Memberikan hak administrator kepada seluruh pengguna',
                    'Menggunakan satu akun bersama',
                    'Memberikan akses berdasarkan senioritas saja',
                ],
                [
                    'Password dan kode dari aplikasi authenticator merupakan contoh?',
                    'Multi-factor authentication',
                    'Single sign-on',
                    'Single-factor authentication',
                    'Role-based authorization',
                ],
                [
                    'Password pengguna sebaiknya disimpan menggunakan?',
                    'Password hashing yang kuat dan salted',
                    'Plain text',
                    'Base64 encoding',
                    'Enkripsi simetris dengan key yang disimpan bersama data',
                ],
                [
                    'Praktik yang efektif mencegah SQL injection pada query aplikasi adalah?',
                    'Menggunakan parameterized query atau prepared statement',
                    'Menggabungkan input langsung ke string SQL',
                    'Menyembunyikan pesan error saja',
                    'Mengubah nama tabel secara berkala',
                ],
                [
                    'HTTPS membantu melindungi komunikasi antara browser dan server terutama melalui?',
                    'TLS',
                    'DNS',
                    'FTP',
                    'ARP',
                ],
                [
                    'Server memiliki kerentanan yang sudah diperbaiki vendor. Tindakan mitigasi yang paling tepat adalah?',
                    'Menerapkan security patch setelah pengujian yang sesuai',
                    'Menonaktifkan logging',
                    'Mengabaikan patch selama aplikasi masih berjalan',
                    'Mengubah password pengguna tanpa memperbaiki kerentanan',
                ],
            ],
            'ti-machine-learning' => [
                [
                    'Model sangat baik pada data training tetapi buruk pada data baru. Kondisi ini disebut?',
                    'Overfitting',
                    'Underfitting',
                    'Regularization',
                    'Feature scaling',
                ],
                [
                    'Model yang belajar dari data berlabel termasuk?',
                    'Supervised learning',
                    'Unsupervised learning',
                    'Reinforcement learning saja',
                    'Dimensionality reduction',
                ],
                [
                    'Tujuan memisahkan training set dan test set adalah?',
                    'Mengevaluasi kemampuan model pada data yang tidak digunakan untuk training',
                    'Menggunakan test set untuk menyesuaikan parameter selama training',
                    'Meningkatkan jumlah fitur',
                    'Menjamin model tidak dapat overfit',
                ],
                [
                    'Pada klasifikasi penyakit yang jarang terjadi, metrik yang membantu menilai berapa banyak kasus positif sebenarnya berhasil ditemukan adalah?',
                    'Recall',
                    'Accuracy saja',
                    'R-squared',
                    'Mean squared error',
                ],
                [
                    'Cross-validation terutama digunakan untuk?',
                    'Mengevaluasi kestabilan performa model pada beberapa pembagian data',
                    'Menggantikan seluruh test set final',
                    'Menambah label secara otomatis',
                    'Menghapus kebutuhan preprocessing',
                ],
                [
                    'Algoritma yang sensitif terhadap skala fitur seperti k-nearest neighbors sering memperoleh manfaat dari?',
                    'Feature scaling',
                    'Menghapus semua fitur numerik',
                    'Menambah nilai acak',
                    'Mengubah target menjadi fitur',
                ],
            ],
            'ti-data-science' => [
                [
                    'Dataset memiliki banyak nilai kosong sebelum analisis. Langkah yang paling tepat adalah?',
                    'Menganalisis pola missing value lalu menentukan penanganan yang sesuai',
                    'Mengganti seluruh missing value dengan nol tanpa analisis',
                    'Menghapus semua baris secara otomatis',
                    'Mengabaikan missing value dalam seluruh kondisi',
                ],
                [
                    'Menggunakan informasi dari data test ketika membangun fitur training dapat menyebabkan?',
                    'Data leakage',
                    'Regularization',
                    'Cross-validation',
                    'Feature scaling',
                ],
                [
                    'Exploratory Data Analysis terutama dilakukan untuk?',
                    'Memahami pola, distribusi, hubungan, dan anomali pada data',
                    'Membuktikan seluruh hipotesis benar',
                    'Menggantikan tahap pengumpulan data',
                    'Mengoptimalkan model tanpa melihat data',
                ],
                [
                    'Dua variabel memiliki korelasi tinggi. Kesimpulan yang benar adalah?',
                    'Korelasi tidak otomatis membuktikan hubungan sebab-akibat',
                    'Variabel pertama pasti menyebabkan variabel kedua',
                    'Kedua variabel pasti tidak dipengaruhi faktor lain',
                    'Korelasi selalu menunjukkan model prediktif yang baik',
                ],
                [
                    'Validation set biasanya digunakan untuk?',
                    'Membantu pemilihan model atau hyperparameter sebelum evaluasi final',
                    'Menjadi pengganti data training',
                    'Digunakan hanya setelah model masuk production',
                    'Menghilangkan kebutuhan test set',
                ],
            ],
            'ti-computer-vision' => [
                [
                    'Dalam klasifikasi citra, data augmentation umumnya digunakan untuk?',
                    'Menambah variasi data training secara terkontrol',
                    'Menghapus seluruh label gambar',
                    'Menggantikan data validation',
                    'Mengubah tugas klasifikasi menjadi clustering',
                ],
                [
                    'Tugas yang menentukan lokasi sekaligus kelas beberapa object pada gambar disebut?',
                    'Object detection',
                    'Image classification',
                    'Image compression',
                    'Optical flow saja',
                ],
                [
                    'Operasi convolution pada CNN terutama membantu model untuk?',
                    'Mengekstraksi pola lokal seperti edge dan fitur visual',
                    'Mengurutkan file gambar',
                    'Mengubah label menjadi teks',
                    'Menyimpan dataset pada database',
                ],
                [
                    'Tugas yang memberikan label kelas pada setiap pixel gambar disebut?',
                    'Semantic segmentation',
                    'Image classification',
                    'Object tracking',
                    'Image retrieval',
                ],
                [
                    'Menggunakan model yang telah dilatih pada dataset besar lalu menyesuaikannya untuk dataset baru disebut?',
                    'Transfer learning',
                    'Random initialization wajib',
                    'Data leakage',
                    'Hard coding feature',
                ],
            ],
        ];
    }
}
